server:
  port: 80


spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/customermng?serverTimezone=UTC
      username: root
      password: xgrc0295
    hikari:
      data-source-properties:
        multiStatements: true



mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      table-prefix: tb_


  #mp日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.itzyb.domain



